name: Node CI

on: [push, pull_request]

defaults:
  run:
    working-directory: backend
        
jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Start Docker for Mongodb
        run: docker run -d -p 27017:27017 mongo
      - name: yarn install and test
        run: |
          yarn
          yarn test
        env:
          CI: true